spring.application.name=moblix
server.port=8080

#configuration for the database
spring.datasource.url=jdbc:postgresql://pg-mateuszpelczar022-617e.h.aivencloud.com:26034/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_0PCR8zm7l7t7dUK_PK0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect  # Auto-detected by Hibernate
spring.jpa.show-sql=true

# Hibernate JTA platform (optional - removes warning)
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

#jwt configuration
jwt.secret=56578345##$%*&&)(*)(*#)@@@*&*&%)*(&$$$$$)7778802312@@***&&
jwt.expiration=86400000
#24 godziny w milisekundach

# File upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
file.upload-dir=uploads/images

#debug=true