# backend/src/main/resources/application-prod.properties
spring.application.name=moblix
server.port=8080


# Database - konfiguracja
spring.datasource.url=jdbc:postgresql://pg-mateuszpelczar022-617e.h.aivencloud.com:26034/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_AXLUC-q9ZO_ooruiol3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

# JWT
jwt.secret=56578345##$%*&&)(*)(*#)@@@*&*&%)*(&$$$$$)7778802312@@***&&
jwt.expiration=86400000

# File upload ustawienia
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
file.upload-dir=uploads/images

# Debug OFF
debug=false

# Logging - poziom limitow aby uniknac wrazliwych danych
logging.level.org.hibernate=ERROR
