spring.application.name=moblix
server.port=8082

#configuration for the database
spring.datasource.url=jdbc:postgresql://pg-mateuszpelczar022-617e.h.aivencloud.com:26034/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_0PCR8zm7l7t7dUK_PK0
#${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# jwt key
jwt.secret=klGVszAyvQRl1LaXTpxUZnZTy3utaIoJwZjEdWrAmC
#(24 godziny w ms)
jwt.expiration=86400000 

